Add support for str_len
RedisJSON/RedisDoc pull request #20
Opened 2019-02-20 14:43 UTC by gkorland

2019-02-20 15:35 UTC, gkorland commented
fix #14

2019-03-02 21:41 UTC, gkorland commented
@gavrie

2019-03-03 12:37 UTC, gavrie requested changes

2019-03-03 12:37 UTC, gavrie commented on src/lib.rs
> +        Some(doc) => RedisValue::Integer(doc.str_len(&path)? as i64),
There is no need to create a `RedisValue` explicitly.
The idea is to rely on the `From` converters defined in `redismodule-rs/redismodule.rs` together with the `into` method:

```
Some(doc) => (doc.str_len(&path)? as i64).into(),
```

In fact, it may be best to add a converter there for `usize` as well so there will be no need to cast to `i64` first:
```
impl From<usize> for RedisValue {
    fn from(i: usize) -> Self {
        (i as i64).into()
    }
}
```

Then the code here becomes:
```
Some(doc) => doc.str_len(&path)?.into(),
```

2019-03-03 12:37 UTC, gavrie commented on src/redisjson.rs
> +                    0 // the value is not a String
Wouldn't the Redis-like behavior be to return a `WRONGTYPE` error, similar to calling `STRLEN` on a non-string key?

2019-03-03 12:37 UTC, gavrie commented on src/redisjson.rs
> +                    serde_json::to_string(&doc)?.len() - 2 // removes ""
You don't need to use `serde_json::to_string` here: That is meant to serialize any value *to* JSON.
You already have JSON here: If the underlying value is a `String`, you can get it with `doc.as_str()`.
This way you also don't get the extra quotes, so no need to remove them.

This way, the whole `if/else` can be replaced by:
```
doc.as_str().map_or(0, |d| d.len());
```

But see the next comment.

2019-03-04 21:42 UTC, merged