Updated README
RedisJSON/RedisDoc pull request #84
Opened 2020-03-05 18:38 UTC by simonprickett

Changed the "Run" section to reflect that Cargo builds a .dylib file not a .so file.

2020-03-05 18:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisJSON/RedisJSON2?pullRequest=84) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisJSON/RedisJSON2?pullRequest=84) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisJSON/RedisJSON2?pullRequest=84) it.</sub>

2020-03-05 22:11 UTC, gkorland requested changes

2020-03-05 22:11 UTC, gkorland commented on README.md
> +redis-server --loadmodule ./target/release/libredisjson.dylib
that is only relevant to MacOS, I would have add two lines, one for linux and one for MacOS

2020-03-06 00:21 UTC, simonprickett commented on README.md
> +redis-server --loadmodule ./target/release/libredisjson.dylib
Thanks @gkorland - updated.

2020-03-08 09:44 UTC, gkorland approved these changes

2020-03-08 09:44 UTC, merged